/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartComponent: typeof import('./src/components/charts/ChartComponent.vue')['default']
    Dashboard: typeof import('@/modules/dashboard/views/DashboardMain.vue')['default']
    DashboardDataLink: typeof import('./src/modules/dashboard/views/DashboardDataLink.vue')['default']
    DashboardMain: typeof import('./src/modules/dashboard/views/DashboardMain.vue')['default']
    DashboardNotice: typeof import('./src/modules/dashboard/views/DashboardNotice.vue')['default']
    DashboardPolicy: typeof import('./src/modules/dashboard/views/DashboardPolicy.vue')['default']
    DashboardUseInfo: typeof import('./src/modules/dashboard/views/DashboardUseInfo.vue')['default']
    GnbDropdownMenu: typeof import('./src/layout/components/GnbDropdownMenu.vue')['default']
    GnbSimpleMenu: typeof import('./src/layout/components/GnbSimpleMenu.vue')['default']
    LineChartComponent: typeof import('./src/components/charts/LineChartComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesList: typeof import('./src/components/SalesList.vue')['default']
    TableBasicCompoment: typeof import('./src/components/TableBasicCompoment.vue')['default']
    TableBasicComponent: typeof import('./src/components/table/TableBasicComponent.vue')['default']
    TableComponent: typeof import('./src/components/table/TableComponent.vue')['default']
    UseInfoComponent: typeof import('./src/modules/dashboard/views/component/UseInfoComponent.vue')['default']
  }
}
